before_install:
- openssl aes-256-cbc -K $encrypted_0b3a5b5acbf1_key -iv $encrypted_0b3a5b5acbf1_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
#- mv application-prod.yml src/main/resources/config/application-prod.yml
- mv lingling.pem /tmp/deploy_key
language: java
script:
- mvn clean package
#- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
addons:
  ssh_known_hosts: ec2-34-249-81-249.eu-west-1.compute.amazonaws.com
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
deploy:
- provider: script
  skip_cleanup: true
  script: rsync --quiet $TRAVIS_BUILD_DIR/target/backend*.jar ubuntu@ec2-34-249-81-249.eu-west-1.compute.amazonaws.com:~ && ssh-agent -k
#  on:
#    tags: true

